### ISSUE TITLE
[0b05:1825] ASUSTek Computer, Inc. Qualcomm Atheros QCA61x4A Bluetooth 4.1 Works

### ISSUE THREAD

**Issue by oblitum** [RehabMan/OS-X-BrcmPatchRAM#47]
See https://github.com/the-darkvoid/BrcmPatchRAM/issues/41. I'm duplicating it here because it's a bit confusing how both projects are evolving in different repositories.

**Comment by RehabMan** [comment]
duplicating the content from that issue:

I have an ASUS ROG MAXIMUS IX FORMULA motherboard and the kexts work for causing the on-board Qualcomm Atheros QCA61x4A to recognize my Magic Mouse. It's working on macOS High Sierra 10.13.2. I'm just reporting so that it becomes listed as tested. Before the installation the Bluetooth controller was reported as functional by macOS but it couldn't scan/pair any device.

I've just put BrcmPatchRAM2.kext and BrcmFirmwareData.kext on /EFI/CLOVER/kexts/Other because I prefer to leave these extra Hackintosh kexts apart from the OS partition if possible, but I notice that the README highlights that BrcmFirmwareRepo.kext on /System/Library/Extensions is the preferred method and it's much less memory hungry, so..., is it that much better? I have 16GB RAM and I didn't get how a simple kext can be that memory hungry to my system, or is it about the controller's memory? Is there a more detailed drawback of sticking to BrcmFirmwareData.kext since I can just put it on Clover besides BrcmPatchRAM2.kext?

**Comment by RehabMan** [comment]
BrcmPatchRAM2.kext will not match against 0b05:1825, as it is not in the Info.plist.
Installing those kexts will have no effect.
If you think it is having an effect on your system, perhaps you are mistaken regarding the vendor/product-id.

BrcmFirmwareData.kext uses more memory as it includes all firmwares for all supported devices instead of loading from disk on demand as BrcmFirmwareRepo.kext does.

**Comment by oblitum** [comment]
OK thanks for the info. So then, I may have not checked it properly without the kexts, I will try again and see.

**Comment by oblitum** [comment]
Will confirm back my experience.

**Comment by oblitum** [comment]
I just confirmed, tried multiple boots without the kexts, and with just `BrcmPatchRAM2.kext`, bluetooth won't recognize any devices trying to pair. Once I put the two kexts back in Clover and reboot, bluetooth readily recognizes my magic mouse and I can pair it. Whatever the two kexts are doing in my system, it's what's making my bluetooth to work.

**Comment by oblitum** [comment]
Regarding the vendor:product tuple, I get it from my main partition running linux:

```
~ ❯❯❯ lsusb | grep Bluetooth
Bus 001 Device 008: ID 0b05:1825 ASUSTek Computer, Inc. Qualcomm Bluetooth 4.1
```

**Comment by oblitum** [comment]
My suspicion is that the specific product id while not being listed in the `Info.plist`, is still [serving to provide a Probe Score](https://developer.apple.com/library/content/qa/qa1076/_index.html) to load a best driver/firmware that happens to still work on this device.

**Comment by RehabMan** [comment]
A kext which has no match for a certain device will have no effect.
You should use the forums and provide complete problem reporting data.
Sorry, but we must deal with reality here.

For example on tmx:
Read FAQ, "Problem Reporting" again.  Carefully.  Attach all requested files/output.
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
Use the tool mentioned in the FAQ, that way it is less likely you'll omit something.

**Comment by oblitum** [comment]
There are several matches in the [probe score table samples](https://developer.apple.com/library/content/qa/qa1076/_index.html) without product id. I don't know how this works in detail as macOS isn't my main platform, and your assertions seem to conflict with official docs. Anyway. Putting these two kexts in place is, without a doubt, what brings my Bluetooth to life, so thank you and @the-darkvoid for it. Just wanted to report and leave it at that without further digging.

**Comment by RehabMan** [comment]
The fact remains that BrcmPatchRAM kexts have no support for 0b05:1825.
A kext cannot have an effect without an IOKitPersonality match for the device in question.
Period.

You have something else going on.

**Comment by chwzr** [comment]
I have the same chip (QCA61x4A) onboard, and  initially it was not working on a clean install. But: I plugged in my IOGEAR GBU521 Bluetooth USB Dongle, and then unplugged it.. since then the internal bluetooth worked just fine 👯 

The IOGEAR has following hardware: BCM20702A Chipset, productID 8680, vendorID 2652, firmware version v14 c4096, HCI version 6, HCI revision 4096, LMP version 6, LMP subversion 8718

Just wondering bc its not a Atheros inside the dongle...
Thats on a Acer Swift 7 Laptop (713-51) and I dont have any bcm patch ram kexts in my system so I can confirm this is not working bc of this kext...

btw:
I know its not the right place to ask,  but I hope someone here maybe knows something: is there a chance to get Wifi working with QCA61x4A ?

Kind regards
